//DOM connects your HTML world with JS
//WHAT JS DOES IS MAKE A TREE LIKE STRUCTURE OF OUR HTML/CSS and calls it DOM
//DOM IS A PROGRAMMATIC REPRESENTATION OF OUR HTML DOCUMENT WHICH IS SEND BY THE BROWSER AND IT IS THE REAL VIEW OF WHAT WE ARE SEEING IN THE SCREEN AS WELL
//SYNCHRONIZATION OF DOM WITH THE SCREEN IS CONTROLLED BY WEB BROWSER WE CAN'T CONTROL IT BUT WE CAN CONTROL THE DOM WHICH INDIRECTLY CONTROLS THE SCREEN. THATS WHAT WE DO WITH JS

console.log(document);